site_name: spherical

repo_url: https://github.com/moble/spherical

nav:
  - Home: index.md
  - 'Quaternions and Rotations': QuaternionsAndRotations.md
  - 'Spin-weighted Spherical Harmonics': SWSHs.md
  - Calculations:
    - WignerDDerivation.md
    - WignerDMatrices.md
    - 'Polynomials with factorials': PolynomialsWithFactorials.md
  - Conventions:
    - Conventions.md
    - 'Quaternions and Rotations': QuaternionsAndRotations.md
    - EulerAngles.md
    - ComparingConventions.md
    - ComparingMathematica.md
  - API:
    - api/spherical/grid/__init__.py
    - api/spherical/grid/algebra.py
    - api/spherical/grid/ufuncs.py
    - api/spherical/grid/utilities.py
    - api/spherical/modes/__init__.py
    - api/spherical/modes/algebra.py
    - api/spherical/modes/derivatives.py
    - api/spherical/modes/ufuncs.py
    - api/spherical/modes/utilities.py
    - api/spherical/__init__.py
    - api/spherical/multiplication.py
    - api/spherical/recursions/__init__.py
    - api/spherical/recursions/complex_powers.py
    - api/spherical/recursions/wigner3j.py
    - api/spherical/recursions/wignerH.py
    - api/spherical/utilities/mode_conversions.py
    - api/spherical/utilities/operators.py
    - api/spherical/utilities/indexing.py


plugins:
  - mktheapidocs:
      modules:
        spherical:
          section: api
          source_repo: "https://github.com/moble/spherical/blob/master"

theme:
  name: 'readthedocs'

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.arithmatex:
      generic: true
