site_name: spherical

repo_url: https://github.com/moble/spherical

nav:
  - Home: index.md
  - 'Quaternions and Rotations': QuaternionsAndRotations.md
  - 'Spin-weighted Spherical Harmonics': SWSHs.md
  - Calculations:
    - WignerDDerivation.md
    - WignerDMatrices.md
    - 'Polynomials with factorials': PolynomialsWithFactorials.md
  - Conventions:
    - Conventions.md
    - 'Quaternions and Rotations': QuaternionsAndRotations.md
    - EulerAngles.md
    - ComparingConventions.md
    - ComparingMathematica.md
  - API:
    - api/spherical/SWSH/__init__.py
    - api/spherical/SWSH_grids/__init__.py
    - api/spherical/SWSH_grids/algebra.py
    - api/spherical/SWSH_grids/ufuncs.py
    - api/spherical/SWSH_grids/utilities.py
    - api/spherical/SWSH_modes/__init__.py
    - api/spherical/SWSH_modes/algebra.py
    - api/spherical/SWSH_modes/derivatives.py
    - api/spherical/SWSH_modes/ufuncs.py
    - api/spherical/SWSH_modes/utilities.py
    - api/spherical/WignerD/WignerDRecursion.py
    - api/spherical/WignerD/__init__.py
    - api/spherical/__init__.py
    - api/spherical/mode_conversions.py
    - api/spherical/multiplication.py
    - api/spherical/recursions/__init__.py
    - api/spherical/recursions/associated_legendre_functions.py
    - api/spherical/recursions/complex_powers.py
    - api/spherical/recursions/wigner3j.py
    - api/spherical/recursions/wignerH.py 


plugins:
  - mktheapidocs:
      modules:
        spherical:
          section: api
          source_repo: "https://github.com/moble/spherical/blob/master"

theme:
  name: 'readthedocs'

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.arithmatex:
      generic: true
